name: alpha-package

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  alpha-checkout:
    runs-on: ubuntu-latest
    outputs:
      pkg_name: ${{ steps.local_version.outputs.PKG_NAME }}
      pkg_version: ${{ steps.local_version.outputs.VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Local Version
        id: local_version
        run: |
          echo "VERSION=$(cat ${{ github.workspace }}/package.json | jq '.version')" >> $GITHUB_OUTPUT
          echo "PKG_NAME=$(cat ${{ github.workspace }}/package.json | jq '.name')" >> $GITHUB_OUTPUT
  alpha-package:
    runs-on: ubuntu-latest
    needs: alpha-checkout
    if: ${{ contains(needs.alpha-checkout.outputs.pkg_version, 'alpha') || contains(needs.alpha-checkout.outputs.pkg_version, 'beta') || contains(needs.alpha-checkout.outputs.pkg_version, 'rc') }}
    steps: 
      - name: Setup Node
        if: 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [[ $(npm view ${{ format('{0}@{1}', needs.alpha-checkout.outputs.pkg_name, needs.alpha-checkout.outputs.pkg_version) }}) ]]; then
            echo "the package has published."
          else
            pnpm install
            pnpm build
            npm publish --access public
          fi
  
